# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf4828b04024c07b745b454b424a3226968cc71f492cd5d55a024d4b468ac2116a3179538a8b56aa5a475c9410490f49f4459cdaad4d803dbe64b66af80b5b6

test:
  secret_key_base: 0e455c3b701981a70838a3b3f4ac3f85b9d6ba31b22eaed9958be0c7e0301bf893d167fb4613e86b1539284a3f8f81d528014aef7f386bc772ca919dd9033130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
